name: Deploy React Admin to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build React Admin
      run: |
        npm install
        npm run build
    
    - name: Update API URL in config.json
      run: |
        jq '.REACT_APP_API_URL = "${{ secrets.REACT_APP_API_URL }}"' build/config.json > tmp.$$.json && mv tmp.$$.json build/config.json

    - name: Create directory on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo rm -rf /var/www/yateloon-backend/*
          sudo mkdir -p /var/www/yateloon-backend
          sudo chown -R ec2-user:ec2-user /var/www/yateloon-backend

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "build/*"
        target: "/var/www/yateloon-backend"
        strip_components: 1
        overwrite: true

    - name: Set Correct Permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R nginx:nginx /var/www/yateloon-backend
          sudo chmod -R 755 /var/www/yateloon-backend

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: sudo systemctl restart nginx
