name: Deploy to POC Bitbucket Deploy Branch

on:
  push:
    branches:
      - poc-test

jobs:
  build-and-push-bitbucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build React Admin
        run: |
          npm install
          npm run build

      - name: Deploy /build to Bitbucket deploy branch
        run: |
          echo "Username : "${{ secrets.BITBUCKET_USERNAME }}
          # 建立一個乾淨的資料夾來存放 deploy 分支的內容
          mkdir ../deploy-folder
          cp -r build/* ../deploy-folder/
          cd ../deploy-folder

          git init -b deploy
          git config --global user.email "game683001@gmail.com"
          git config --global user.name "Newt Ye"
          git remote add origin https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/game683001/frontend-yateloon.git
          git add .
          git commit -m "Deploy built files"
          git push origin deploy --force
